# Generated by Django 3.1.4 on 2021-06-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0002_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
