# Generated by Django 3.1.4 on 2021-06-16 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0005_history_hno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='Hno',
        ),
    ]
