# Generated by Django 3.1.4 on 2021-06-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bank', '0006_remove_history_hno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='History',
        ),
    ]
